### PR TITLE
Allow overriding of ConnectionHost events and creation

### PR DESCRIPTION
**Pull request by tiggerite**
This would enable other logging options for metrics/alerting and so forth when a connection goes down via ChannelPool to RabbitService constructor

### CODE REVIEW

**Review by tiggerite — COMMENTED** [review]
Probably best to merge this one first if possible.. not sure if the reverting of the other commits would cause conflicts in the second otherwise

**Review by tiggerite — COMMENTED** [review]
Agh as I thought it mucked it up, will fix this tomorrow.

**Comment by tristan-hyams** [comment]
You can close this, I have your changes inbound.

**Comment by tiggerite** [comment]
> You can close this, I have your changes inbound.

Oh ok :) I had fixed it by reverting the reverts, too. Thanks 👍🏻

**Pull request closed without merging**
