### PR TITLE
Add LazyInitialize option to PoolOptions

### PR DESCRIPTION
**Pull request by tiggerite**
This allows construction of Pools without GetAwaiter().GetResult() on async connection/channel creation

### CODE REVIEW

**Comment by tristan-hyams** [comment]
This has existed in previous iterations of CookedRabbit.

The problem was user error became the primary thing I had to deal with. Pool construction was independent of Connectivity... unfortunately can be a useful performance concept if you are delaying actual connectivity till time of use... it became a nightmare to troubleshoot for users. Especially users who went straight into pipeline land. I got tired of it and took a page out of golangs book and just invoked connectivity immediately. This allows you to avoid troubleshooting connectivity problems and bad server setups, to instead being bad code setups, bad URIs, unintentionally bad library usage etc.

You know the ConnectionPool has failed immediate connectivity when created.

Second issue, was directly exposing Connection creation, there is no protection on duplicate calls (there used to be this too for the same reason). Again, bad user usage needs to be guarded against if they call it multiple times in many places.

I love being helpful and I do know the use case and I know the value of initializing a 100 different Connection Pools not on startup. ConnectionPool is basically "safe". Perhaps this is a use case for a second Pool types, that are lazy, adhering to the interface. Would that be agreeable?

**Comment by tristan-hyams** [comment]
Also looking at some of my logic...

... this pool pattern is approaching 1 year old.

I know I am ridiculously faster than nServiceBus already but I think there is some room for redesign for performance improvements AND simplification. (No offense to nServiceBus they have done a great job of abstracting away all patterns).

**Comment by tiggerite** [comment]
Everything you say makes complete sense, and I do like the way golang does things in this regard too. Creating new pools is an option but wouldn't be able to inherit from the current ones due to the setup being called in the constructor.. hmm. 

What about if we made use of AsyncLazy from Nito.AsyncEx.Coordination? Then the classes could lazy initialise transparently to users who wouldn't then have to call methods which are easily forgotten. (I actually did exactly this yesterday with StartAutoPublisherAsync.. so I do know the pain!)

I'll see if I can change the PR to use it, making use of the ExecuteOnRunningThread option, and then we can see what it looks like? Might be the best of  both worlds.

**Comment by tiggerite** [comment]
@houseofcat I've updated it now to use AsyncLazy. ChannelHost was really awkward to do, given the current implementation. Please let me know what you think?

**Comment by tristan-hyams** [comment]
I am going to be fairly busy over the next few days (work and family).

Can you fire one of the high throughput benchmarks or UnitTests and start testing connectivity loss? Some of the edge cases look like they may be getting lost and recovery maybe not be happening as expected.

Something like:
https://github.com/houseofcat/Tesseract/blob/66acd5001885c9a5145f1e9e1b97263be58a832e/tests/HouseofCat.RabbitMQ.IntegrationTests/AutoPublisherTests.cs#L132

You can simulate a connection blip/outage by executing this on localhost (if it has the RabbitMQ server) on Windows in the RabbitMQ \bin location if its not added to $PATH already. There is something similar on Linux that you can probably look up. You should probably trigger it multiple times during the test.

```powershell
rabbitmqctl.bat close_all_connections "suck it long, suck it hard trebek"
```

Couple of things that you are ideally tracking/looking out for.
  1. That the Channels all recover - roughly the same amount of channels more or less exist and are connected shortly after (you could have extra channels on transient channel using consumers but they have their own life cycle).
  2. Making sure Channels recovered aren't all stuck on one Connection either - so evenly distributed still per the original channel creation.
     a. You can verify this in debug and through the management UI. Leaving it paused too long on debug will cause all the connections to drop. You can help your debugging by increasing the heart beat timeout in the config. There is nothing I can do in my library as its a RabbitMQ client thing.
  3. If you published `100,000` the consumer gets `100,000`.

Once you get a feel for the chaos engineering, feel free to test a few other scenarios, like just looping through the connection pool or channel pool and testing channel recovery. I see it's been tweaked.

Also one of the patterns that may make more sense is a converting to a ChannelFactory inside the ConnectionPool. The channels are short lived, but even still have so much boiler plate to setup correctly with EventHandlers and to unset the EventHandlers to prevent memory leaks when they are being replaced. Sitting next to the connections, which are what can be long lived, could simplify some of the complexity with ChannelHost and may stop from needing it attached to a Connection directly. It could simply be in memory map/dictionary of the ChannelFactory in the ConnectionPool. Finally, solving the potential Ack/Nack out of order on the original Channel, would more than likely still be in the ChannelHost but... that's not too terrible and fails predictably when the channel dies. I need to give it more thought.

This worked really well in `golang`.
https://github.com/houseofcat/turbocookedrabbit/blob/master/v2/pkg/tcr/connectionpool.go

If I go that route, I fear most of your changes would be lost. So you may want to leave this as is until I can buy sometime to streamline this a 3rd time and I am assuming that along with streamlining you would really like the ability to defer connectivity till time of use or even channel creation (chained with connection) maybe a desirable option. I may review how Microsoft does it. Couchbase and I had very similar patterns.

**Comment by tiggerite** [comment]
I know the feeling very well about being busy with work and family.. I'll certainly give the tests a go when I get chance, I'm very used to running rabbit in Docker actually and then just stop/starting it to generate errors plus check reconnectivity. I also do use the Management UI quite extensively to check consumers, queues, exchanges, bindings and dead letters ;)

The idea of a ChannelFactory is a good one, I guess I was trying to keep to the current pattern as much as possible given so many things seem to use ChannelHost in its current form (changing all the usages of GetChannel to be async wasn't the most fun!). Yes, I've had similar pain with the event handler off/on pattern too to prevent leaks. 

Your golang implementation is very clean. In fact I'm going to try to convince my work colleagues to use your library in our upcoming golang conversion of a service from C#.. 

As for my changes and the ability to defer connectivity, I really don't mind if they are lost. My main aim is to prevent the sync over async pattern - perhaps a hope in vain because I know the RabbitMQ.Client that we so love is nowhere near full async (although there is a branch full-async and it definitely seems to be the long-term aim, so there is hope). However it would be nice to eliminate them in this library at least; it should allow for easier integration of a full async client if it ever becomes a reality, too. GetAwaiter().GetResult() will always prevent that though, especially in constructors.

**Pull request closed without merging**
