### PR TITLE
Get ConsumerOptions from RabbitService Options

### PR DESCRIPTION
**Pull request by tiggerite**
Removes the need for an unused Consumer in RabbitService (as ConsumerDataflow creates and manages its own). Also RabbitService has its own SerializationProvider (which is required) so may as well use it by default.

### CODE REVIEW

**Review by tristan-hyams — APPROVED** [review]
Yeah looks good as a default option/behavior.

**Comment by tiggerite** [comment]
Please could you push a new version of the nuget package for this @houseofcat ? :) Should be only RabbitMQ.Dataflows - no others needed.

**Comment by tristan-hyams** [comment]
Done with a small tweak and some additional method comments.

**Comment by tiggerite** [comment]
Good shout about allowing a null serialization provider, like you say a very niche case but fair enough as an option. 

Although actually because buildStateBlock is mandatory I think it would blow up with a null one on BuildState<TOut> wouldn't it?

**Pull request merged**
